[package]
name = "http-header-map-api-proof"
version = "0.1.0"
edition = "2021"
publish = false

[features]
http_map_api_leaf = []

[dependencies]
bytes = "=1.11.1"
creusot-std = { path = "../../../../creusot-libs/creusot-std", features = ["bytes-model"] }
http_runtime = { package = "http", path = "../runtime-http" }
