use std::{env, fs, path::PathBuf};
use crate::item;

fn ensure_check_ghost(source: &str, signature: &str, indent: &str) -> (String, bool) {
    assert_eq!(source.matches(signature).count(), 1, "expected unique signature: {signature}");
    let index = source.find(signature).unwrap();
    let already_checked = source[..index]
        .lines()
        .rev()
        .take_while(|line| line.trim_start().starts_with("#["))
        .any(|line| line.contains("check(ghost)"));
    if already_checked {
        (source.to_owned(), false)
    } else {
        (source.replace(signature, &format!("{indent}#[cfg_attr(creusot, check(ghost))]\n{signature}")), true)
    }
}

fn ensure_all_check_ghost(source: &str, signature: &str, indent: &str) -> (String, usize, usize) {
    let positions = source.match_indices(signature).map(|(index, _)| index).collect::<Vec<_>>();
    assert!(!positions.is_empty(), "missing signature: {signature}");
    let mut result = source.to_owned();
    let mut inserted = 0;
    let mut existing = 0;
    for index in positions.into_iter().rev() {
        let already_checked = result[..index]
            .lines()
            .rev()
            .take_while(|line| line.trim_start().starts_with("#["))
            .any(|line| line.contains("check(ghost)"));
        if already_checked {
            existing += 1;
        } else {
            result.insert_str(index, &format!("{indent}#[cfg_attr(creusot, check(ghost))]\n"));
            inserted += 1;
        }
    }
    (result, inserted, existing)
}

pub fn generate(bytes_mut: &str, generated: &mut String) {
    let root = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap())
        .join("../../..").canonicalize().unwrap();
    let out = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let mut modules = String::new();
    let mut audit = String::new();
    for (module, path, signatures) in [
        ("raw_vec", "src/ownership_proof/raw_vec.rs", vec![
            "pub(crate) unsafe fn borrow_bound<'a>(",
            "pub(crate) unsafe fn borrow_empty_bound<'a>("]),
        ("shared_protocol", "src/ownership_proof/shared_protocol.rs", vec![
            "pub(crate) unsafe fn borrow_packet<'a>("]),
        ("provenance_specs", "src/provenance_specs.rs", vec![
            "pub(crate) fn pointer_addr<T>("]),
    ] {
        println!("cargo:rerun-if-changed={}", root.join(path).display());
        let mut source = fs::read_to_string(root.join(path)).unwrap();
        for signature in signatures {
            let expected = if module == "provenance_specs" { 2 } else { 1 };
            assert_eq!(source.matches(signature).count(), expected);
            let (updated, inserted, existing) = ensure_all_check_ghost(&source, signature, "");
            source = updated;
            audit.push_str(&format!("{path}: {inserted} check(ghost) additions, {existing} already present on {signature}; original body and contracts unchanged\n"));
        }
        // Only rebind the native allocation module location after relocating
        // this otherwise exact source file into OUT_DIR.
        if module == "raw_vec" {
            source = source.replace("#[path = \"../allocation_ops.rs\"]",
                &format!("#[path = {:?}]", root.join("src/allocation_ops.rs")));
        }
        let destination = out.join(format!("readonly_{module}.rs"));
        fs::write(&destination, source).unwrap();
        modules.push_str(&format!("#[path = {:?}]\nmod {module};\n", destination));
    }
    for signature in ["    fn as_slice(&self) -> &[u8] {", "    fn as_ref(&self) -> &[u8] {",
        "    fn kind(&self) -> usize {"] {
        let (updated, inserted) = ensure_check_ghost(generated, signature, "    ");
        *generated = updated;
        audit.push_str(&format!("generated BytesMut::{signature}: {}check(ghost)\n",
            if inserted { "added " } else { "existing " }));
    }
    *generated = generated.replace("    fn as_ref(&self) -> &[u8] {",
        "    #[cfg_attr(creusot, ensures(result.deep_model() == self.deep_model()))]\n    fn as_ref(&self) -> &[u8] {");
    let deref = item(bytes_mut, "impl Deref for BytesMut {");
    let (deref, inserted) = ensure_check_ghost(&deref, "    fn deref(&self) -> &[u8] {", "    ");
    let adapted = deref.replace("    fn deref(&self) -> &[u8] {",
        "    #[cfg_attr(creusot, ensures(result.deep_model() == self.deep_model()))]\n    fn deref(&self) -> &[u8] {");
    audit.push_str(&format!("generated BytesMut::deref: {}check(ghost)\n",
        if inserted { "added " } else { "existing " }));
    generated.push_str("use core::ops::Deref;\n");
    generated.push_str(&adapted);
    for marker in ["impl PartialEq<[u8]> for BytesMut {", "impl PartialOrd<[u8]> for BytesMut {",
        "impl PartialEq<BytesMut> for [u8] {", "impl PartialOrd<BytesMut> for [u8] {"] {
        generated.push_str(&crate::comparison_contracts(&item(bytes_mut, marker)));
        generated.push('\n');
    }
    fs::write(out.join("readonly_modules.rs"), modules).unwrap();
    fs::write(out.join("readonly_purity_changes.txt"), audit).unwrap();
}
