[main]
magic = 14
memlimit = 1000
running_provers_max = 1
timelimit = 5.000000

[partial_prover]
name = "Alt-Ergo"
path = "/workspace/proof-tools/creusot-data/bin/alt-ergo"
version = "2.6.2"

[partial_prover]
name = "CVC4"
path = "/workspace/proof-tools/creusot-data/bin/cvc4"
version = "1.8"

[partial_prover]
name = "CVC5"
path = "/workspace/proof-tools/creusot-data/bin/cvc5"
version = "1.3.1"

[partial_prover]
name = "Z3"
path = "/workspace/proof-tools/creusot-data/bin/z3"
version = "4.15.3"

[strategy]
code = "start:
c Alt-Ergo,2.6.2 .2 1000
c Z3,4.15.3 .2 1000
c CVC5,1.3.1 .2 1000
c CVC4,1.8 .2 1000
c Alt-Ergo,2.6.2 1 1000 | Z3,4.15.3 1 1000 | CVC5,1.3.1 1 1000 | CVC4,1.8 1 1000
t compute_specified start
t split_vc start
c Alt-Ergo,2.6.2 2 4000 | Z3,4.15.3 2 4000 | CVC5,1.3.1 2 4000 | CVC4,1.8 2 4000
"
desc = "Automatic@ run@ of@ provers@ and@ most@ useful@ transformations"
name = "Creusot_Auto"
shortcut = "4"

[prover]
name = "Z3-Pow2Pruned"
version = "4.15.3"
command = "/workspace/httparse-tool-rebuild/string-model/creusot-data/bin/z3 -smt2 -T:%t sat.random_seed=42 nlsat.randomize=false smt.random_seed=42 -st %f"
command_steps = "/workspace/httparse-tool-rebuild/string-model/creusot-data/bin/z3 -smt2 sat.random_seed=42 nlsat.randomize=false smt.random_seed=42 -st rlimit=%S %f"
driver = "/tmp/itoa-proof-config.BtyFio/creusot/z3-pow2pruned.drv"
