source /workspace/proof-tools/activate.sh
export RUSTUP_TOOLCHAIN=nightly-2026-06-22
export CARGO_HOME=/workspace/bytes-proof-tools/cargo
export CREUSOT_DATA_HOME=/workspace/bytes-proof-tools/creusot-data
export XDG_CONFIG_HOME=/workspace/bytes-proof-tools/config
export XDG_CACHE_HOME=/workspace/bytes-proof-tools/cache
export OPAMSWITCH=/workspace/proof-tools/creusot-data
export CARGO_BUILD_JOBS=4
export OCAMLPATH="$CREUSOT_DATA_HOME/lib:/workspace/proof-tools/creusot-data/_opam/lib${OCAMLPATH:+:$OCAMLPATH}"
export CARGO_TARGET_DIR=/workspace/bytes-proof-tools/targets/bytes
export PATH="$CARGO_HOME/bin:$CREUSOT_DATA_HOME/bin:/workspace/proof-tools/creusot-data/_opam/bin:$PATH"
export CAML_LD_LIBRARY_PATH="/workspace/proof-tools/creusot-data/_opam/lib/stublibs:/workspace/proof-tools/creusot-data/_opam/lib/ocaml/stublibs:/workspace/proof-tools/creusot-data/_opam/lib/ocaml${CAML_LD_LIBRARY_PATH:+:$CAML_LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="/workspace/proof-tools/system/usr/lib/x86_64-linux-gnu:$RUSTUP_HOME/toolchains/nightly-2026-06-22-x86_64-unknown-linux-gnu/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
