[package]
name = "bytes-original-boxed-automatic-drop"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
creusot-std = "=0.13.0"

[workspace]

[features]
public_constructor = []
native_b1box = []
negative_wrong_selected_vtable = []
negative_wrong_constructor_content = []
negative_missing_free = []
negative_wrong_free_pointer = []
negative_wrong_free_size = []
negative_missing_untag = []
negative_raw_as_static = []
negative_raw_as_arc = []
negative_duplicate_free = []
