[package]
name = "bytes-actual-uninit-slice"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
doctest = false

[dependencies]
creusot-std = "=0.13.0"

[features]
wrong_copy_model = []
remaining_apis = []
range_full_index = []
range_bounds_index = []
range_from_index = []
range_to_index = []
range_to_inclusive_index = []
range_inclusive_index = []
bad_deinitialize = []
bound_raw = []
bad_bound_raw_pointer = ["bound_raw"]

[workspace]
