[package]
name = "tokio-set-once-verification"
version = "1.52.3"
edition = "2021"
publish = false

[package.metadata.verus]
verify = true

[lib]
path = "src/lib.rs"

[dependencies]
vstd = { git = "https://github.com/verus-lang/verus.git", rev = "31579f0b8542a8a9ae4ae5604c16107ccde23ef2" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(verus_only)"] }
