verif/httparse_derived_traits_harness_rlib/impl_PartialEq_for_SignedI8/eq.coma
verif/httparse_derived_traits_harness_rlib/impl_PartialEq_for_SignedI8/eq__refines.coma
verif/httparse_derived_traits_harness_rlib/impl_Eq_for_SignedI8/assert_fields_are_eq.coma
verif/httparse_derived_traits_harness_rlib/impl_PartialEq_for_SignedI16/eq.coma
verif/httparse_derived_traits_harness_rlib/impl_PartialEq_for_SignedI16/eq__refines.coma
verif/httparse_derived_traits_harness_rlib/impl_Eq_for_SignedI16/assert_fields_are_eq.coma
verif/httparse_derived_traits_harness_rlib/error_equal_same_variant.coma
verif/httparse_derived_traits_harness_rlib/error_equal_different_variants.coma
verif/httparse_derived_traits_harness_rlib/repr_i8_equal_same_variant.coma
verif/httparse_derived_traits_harness_rlib/repr_i8_equal_different_variants.coma
verif/httparse_derived_traits_harness_rlib/repr_i16_equal_same_variant.coma
verif/httparse_derived_traits_harness_rlib/repr_i16_equal_different_variants.coma
verif/httparse_derived_traits_harness_rlib/repr_i8_discriminant_math.coma
verif/httparse_derived_traits_harness_rlib/repr_i8_discriminant_bitwise.coma
verif/httparse_derived_traits_harness_rlib/repr_i16_discriminant_math.coma
verif/httparse_derived_traits_harness_rlib/repr_i16_discriminant_bitwise.coma
